[package]
name = "lpc-usbd"
version = "0.1.0"
edition = "2021"
authors = ["Alexis Marquet <alexis@alexismarquet.com>"]
description = "'usb-device' implementation for LPC microcontrollers"
license = "MIT"
repository = "https://github.com/lpc-rs/lpc-usbd"
readme = "README.md"
keywords = ["no-std", "embedded", "usb"]

[dependencies]
vcell = "0.1.2"
cortex-m = "0.7.1"
usb-device = "0.2.8"

[dev-dependencies]
lpc546xx-hal = { version = "0.2.0", features = ["mcu-LPC54608J512ET180"] }
